name: edificion247
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1  

environment:
  sdk: ">=2.7.0 <3.0.0" 
 
dependencies:  
  flutter: 
    sdk: flutter
  gradient_app_bar: 
  splashscreen:
  table_calendar:
  flutter_svg:
  image_picker: 0.6.0+8
  geolocator: 
  usage: 
  toast:
  page_transition: 
  flutter_icons: ^1.0.0
  http: ^0.12.0+4
  flutter_clean_calendar: ^1.0.1
  back_button_interceptor: ^4.2.3
  progress_dialog: 
  flutter_launcher_icons:
  qr_flutter: ^3.1.0
  firebase_core: ^0.4.4
  cloud_firestore: ^0.13.4+2 
  firebase_messaging: ^6.0.13
  flushbar: 
  esys_flutter_share: ^1.0.2
  path_provider:


  
  
 

  

  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart: 
  flutter_map: 
  
  fluttertoast:
  shared_preferences:

flutter_icons:
  image_path: "recursos/imagenes/launcher.png" 
  android: true 
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: CenturyGothic
       fonts:
        - asset: recursos/fonts/CenturyGothic.ttf

  assets: 
      - recursos/imagenes/logo.png 
      - recursos/imagenes/logoApp.png 
      - recursos/imagenes/user-foto-not.png
      - recursos/imagenes/facebook.png 
      - recursos/imagenes/twitter.png 
      - recursos/imagenes/LogoSF.png 
      - recursos/imagenes/LogoEmpresa.png 
      - recursos/imagenes/launcher.png
      - recursos/imagenes/profile.png
      - recursos/imagenes/imgqr.png
      - recursos/imagenes/profile.png
      - recursos/imagenes/calendar-icon-png-4096.png
      - recursos/imagenes/calendar.png
      - recursos/imagenes/email.png
      - recursos/imagenes/exit.png
      - recursos/imagenes/factura.png
      - recursos/imagenes/home.png
      - recursos/imagenes/qr.png
      - recursos/imagenes/warning.png
      - recursos/imagenes/adminicon.png 
      - recursos/imagenes/residenteicon.png
      - recursos/imagenes/admin.png
      - recursos/imagenes/personas.png
      - recursos/imagenes/junta.png
      - recursos/imagenes/trespersonasicon.jpg
      - recursos/imagenes/iconreserva.png
      - recursos/imagenes/facturaicon.png
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
